### ISSUE TITLE
ability to provide a custom allocator to inner std::vector

### ISSUE THREAD

**Issue by mean-ui-thread** [Lunarsong/StructureOfArrays#10]
use case: for performance reason, the use of a custom allocator that doesn't initialize the data for POD members can be desired, especially when large amount of data needs to be pushed into the SOA, where `resize` makes more sense to use than pushing every slices one by one using `push_back`, and we do not want `resize` to initialize the data to any value because we are going to overwrite that memory anyway.

**Comment by mean-ui-thread** [comment]
to be honest with you, I don't know if there is a clean way to do this. And also, I remember you talking about replacing all the vectors by a single contiguous buffer instead, so maybe this request is not reasonable. If that is the case, feel free to reject this request.

**Comment by mean-ui-thread** [comment]
I changed my mind! 😁

**Comment by Lunarsong** [comment]
Hey! I do want to add options for allocators. It's something I need in my game engine also, but I'm going to take a bit of time doing this as there are some other things I need to finish first.
